---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    p: "no:pytest-ansible"
    verbose: true