---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if WordPress files exist
      ansible.builtin.stat:
        path: /var/www/wordpress/wp-config.php
      register: wp_config
      failed_when: not wp_config.stat.exists

    - name: Check WordPress configuration
      ansible.builtin.command: grep "DB_NAME" /var/www/wordpress/wp-config.php
      register: wp_db_config
      changed_when: false
      failed_when: "'wordpress_db' not in wp_db_config.stdout"

    - name: Check WordPress permissions
      ansible.builtin.stat:
        path: /var/www/wordpress
      register: wp_dir
      failed_when: 
        - wp_dir.stat.owner != "www-data"
        - wp_dir.stat.group != "www-data"
