---
- name: Install MariaDB and dependencies
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Ensure MySQL socket directory exists
  ansible.builtin.file:
    path: /var/run/mysqld
    state: directory
    mode: '0755'
    owner: mysql
    group: mysql

- name: Check if MariaDB is running
  ansible.builtin.command: pgrep mysqld
  register: mariadb_process
  changed_when: false
  failed_when: false

- name: Start MariaDB service
  ansible.builtin.command: mysqld_safe &
  async: 45
  poll: 0
  changed_when: false
  when: mariadb_process.rc != 0

- name: Wait for MariaDB to be ready
  ansible.builtin.wait_for:
    port: 3306
    timeout: 30

- name: Create admin user for MariaDB
  community.mysql.mysql_user:
    name: admin
    password: "{{ mariadb_admin_password }}"
    host: localhost
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: admin
    login_password: "{{ mariadb_admin_password }}"

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    host: localhost
    state: present
    login_user: admin
    login_password: "{{ mariadb_admin_password }}"

- name: Check MySQL user permissions
  community.mysql.mysql_query:
    login_user: admin
    login_password: "{{ mariadb_admin_password }}"
    query: "SHOW GRANTS FOR '{{ mysql_user }}'@'localhost'"
  register: user_permissions

- name: Flush privileges
  community.mysql.mysql_query:
    login_user: admin
    login_password: "{{ mariadb_admin_password }}"
    query: FLUSH PRIVILEGES
