---
- name: Download WordPress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Set correct permissions for WordPress files
  ansible.builtin.file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    recurse: yes

- name: Copy WordPress config file
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data

- name: Ensure WordPress directory exists
  ansible.builtin.file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data

- name: Generate WordPress salts
  ansible.builtin.command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt
  changed_when: false
