---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/debian:stable
    pre_build_image: true
    privileged: true
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    p: "no:pytest-ansible"
    verbose: true
