---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if MariaDB is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present
      check_mode: true
      register: mariadb_check
      failed_when: mariadb_check.changed

    - name: Check if MariaDB is running
      ansible.builtin.service:
        name: mariadb
        state: started
      check_mode: true
      register: mariadb_status
      failed_when: mariadb_status.changed

    - name: Check if WordPress database exists
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
      check_mode: true
      register: db_check
      failed_when: db_check.changed
