---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if Apache is installed
      ansible.builtin.package:
        name: apache2
        state: present
      check_mode: true
      register: apache_check
      failed_when: apache_check.changed

    - name: Check if Apache is running
      ansible.builtin.service:
        name: apache2
        state: started
      check_mode: true
      register: apache_status
      failed_when: apache_status.changed

    - name: Check if PHP is installed
      ansible.builtin.package:
        name: php
        state: present
      check_mode: true
      register: php_check
      failed_when: php_check.changed
