---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check if essential packages are installed
      ansible.builtin.package:
        name:
          - curl
          - vim
          - htop
          - ufw
        state: present
        check_mode: true
      register: package_check
      failed_when: package_check.changed

    - name: Check if UFW is enabled
      ansible.builtin.command: ufw status
      register: ufw_status
      changed_when: false

    - name: Fail if UFW is not active
      fail:
        msg: "UFW is not active. Review your post_installation role."
      when: "'Status: active' not in ufw_status.stdout"

    - name: Check if webadmin user exists
      ansible.builtin.getent:
        database: passwd
        key: webadmin
      register: webadmin_user
      failed_when: webadmin_user.failed
