---
- name: Install Apache and PHP
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Enable Apache modules
  ansible.builtin.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - ssl

- name: Create Apache virtual host configuration
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify: Reload Apache

- name: Enable WordPress site
  ansible.builtin.file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link
  notify: Reload Apache

- name: Ensure Apache is running and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
