---
- name: Install Apache and PHP
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Enable Apache modules
  ansible.builtin.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - ssl

- name: Create Apache virtual host configuration
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify: Reload Apache

- name: Enable WordPress site
  ansible.builtin.file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link
  notify: Reload Apache

- name: Check if Apache is running
  ansible.builtin.command: pgrep apache2
  register: apache_status
  changed_when: false
  failed_when: false

- name: Start Apache if not running
  ansible.builtin.command: apache2ctl start
  when: apache_status.rc != 0

- name: Ensure Apache is running
  ansible.builtin.command: apache2ctl -k start
  changed_when: false